### ISSUE TITLE
MUMPS dylib won't load because linked to old openblas

### ISSUE THREAD

**Issue by wrs28** [brewsci/homebrew-num#47]
I found this issue when trying to access MUMPS in Julia, filing [this issue](https://github.com/JuliaSmoothOptimizers/MUMPS.jl/issues/43).

@dpo was helpful and pointed me to a likely issue with need to rebuild dependencies of brewsci-mumps.

I'm just filing this here for completeness.

**Comment by zbeekman** [comment]
FYI, homebrew-core is migrating to using OpenBLAS, so so eventually we could migrate mumps to core depending on what options/libs it should be built with.

**Comment by wrs28** [comment]
Recent `brew upgrade` fixed the issue.
