### ISSUE TITLE
Error when compiling brewsci-mumps from brewsci/num

### ISSUE THREAD

**Issue by dumontsrg** [brewsci/homebrew-num#57]
When I try to install brewsci-mumps (mumps-5.2.1), I obtain the following error:

make alllib RANLIB=echo OPTF=-O CDEFS=-DAdd_ LMETISDIR=/usr/local/opt/brewsci-parmetis/lib IMETIS=/usr/local/opt/brewsci-parmetis/include LMETIS=-L/usr/local
Last 15 lines from /Users/serge/Library/Logs/Homebrew/brewsci-mumps/01.make:
  815 |         CALL MUMPS_ICOPY_64TO32(XADJ8, NVTX, PARENT)
      |                                             2  
Error: Element of assumed-shape or pointer array as actual argument at (1) cannot correspond to actual argument at (2)
ana_orderings_wrappers_m.F:114:31:

  114 |       CALL METIS_NODEND( NCMP, IPE, IW, FRERE(1),
      |                               1
......
  284 |        CALL METIS_NODEND( NCMP, IPE8, IW, FRERE(1),
      |                                2
Error: Type mismatch between actual argument at (1) and actual argument at (2) (INTEGER(4)/INTEGER(8)).
make[3]: *** [ana_orderings_wrappers_m.o] Error 1
make[2]: *** [c] Error 2
make[1]: *** [mumps_lib] Error 2
make: *** [c] Error 2

Thanks in advance for your response.

**Comment by philippedevloo** [comment]
I also got similar issues. They are related to mpi, although I specifically disabled mpi from the build option:

==> Installing brewsci/num/brewsci-mumps --without-mpi
==> make alllib RANLIB=echo OPTF=-O CDEFS=-DAdd_ LMETISDIR=/usr/local/opt/brewsci-metis/lib IME
Last 15 lines from /Users/philippedevloo/Library/Logs/Homebrew/brewsci-mumps/01.make:
      |                                                                        1
Error: Type mismatch in argument 's' at (1); passed INTEGER(4) to COMPLEX(8)
mpi.f:586:72:

  586 |          CALL MUMPS_COPY_2DOUBLE_PRECISION( SENDBUF, RECVBUF, CNT )
      |                                                                        1
Error: Type mismatch in argument 's' at (1); passed INTEGER(4) to REAL(8)
mpi.f:590:72:

  590 |         CALL MUMPS_COPY_INTEGER8( SENDBUF, RECVBUF, CNT )
      |                                                                        1
Error: Type mismatch in argument 's' at (1); passed INTEGER(4) to INTEGER(8)
make[2]: *** [mpi.o] Error 1
make[1]: *** [libseqneeded] Error 2
make: *** [c] Error 2

**Comment by dumontsrg** [comment]
I found a solution: since I am using gcc-10, I need to add "-fallow-argument-mismatch" in the formula.

**Comment by philippedevloo** [comment]
let us know when you get around doing it...

**Comment by millen1m** [comment]
I had this same issue as brew has updated to gcc-10. I downloaded the mumps formula (https://github.com/brewsci/homebrew-num/blob/master/Formula/brewsci-mumps.rb).
I changed line 35 to: `    make_args = ["RANLIB=echo", "OPTF=-O -fallow-argument-mismatch", "CDEFS=-DAdd_"]`.
Adding the ` -fallow-argument-mismatch`.

I then built mumps from the local formula using `brew install --build-from-source brewsci-mumps.rb`

**Comment by dpo** [comment]
Yes I did the same but bewsci-scalapack also needs to be updated. Feel free to submit a PR.

**Comment by dumontsrg** [comment]
Thank you for your help. It works. Nevertheless, I need to install mumps with "--without-mpi".
And then I obtain the following error:

Error: An exception occurred within a child process:
  Errno::ENOENT: No such file or directory @ dir_chdir - lib/libseq
