### ISSUE TITLE
Import Error with brewsci-superlu-dist

### ISSUE THREAD

**Issue by BridgeRain** [brewsci/homebrew-num#59]
The following is an import error with brewsci-superlu-dist:

````
ImportError: dlopen(/Users/BridgeRain/opt/anaconda3/lib/python3.8/site-packages/openseespy/opensees/mac/opensees.so, 2): Library not loaded: /usr/local/opt/openblas/lib/libopenblasp-r0.3.5.dylib
  
Referenced from: /usr/local/opt/brewsci-superlu-dist/lib/libsuperlu_dist.5.dylib
  
Reason: image not found
````

The latest version of formula "openblas" is 0.3.12 and the corresponding library file is "libopenblasp-r0.3.12.dylib" instead of "libopenblasp-r0.3.5.dylib". This may be the reason of the import error. 

How to solve it?  I think it is related to "libsuperlu_dist.5.dylib".

Thanks in advance for your response.

**Comment by dpo** [comment]
Thanks for the report. It should just be a matter of rebuilding the bottle. We're at SuperLU-Dist 6.4.0 now, so I also upgraded the library in #60.
